name: Emscripten
on: [push]
jobs:
  build_emscripten:
    runs-on: ubuntu-latest
    container: conanio/gcc11-ubuntu16.04:1.39.0 # your docker image
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: pwd
      - run: conan --version
      - run: echo "ğŸ This job's status is ${{ job.status }}."
